## Peer-Reviewed Articles

### Journals

-   Melanie R Weltman, Linda-Marie U Lavenburg, Zhuoheng Han, **Alaa A Alghwiri**, Mitra Mosslemi, Bruce L Rollman, Gary S Fischer, Thomas D Nolin, Jonathan G Yabes, Manisha Jhamb.[Population Health Management and Guideline-Concordant Care in CKD: A Secondary Analysis of K-CHAMP](https://journals.lww.com/jasn/abstract/9900/population_health_management_and.471.aspx). Journal of the American Society of Nephrology, November 2024. DOI: 10.1681/ASN.0000000544

-   Cramer J Kallem, **Alaa A Alghwiri**, Jonathan Yabes, Sarah Erickson, Zhuoheng Han, Maria-Eleni Roumelioti, Jennifer L Steel, Manisha Jhamb, Mark Unruh. [Diurnal and Daily Symptom Variation in Patients with End-Stage Kidney Disease: An Ecological Momentary Assessment Study](https://journals.lww.com/cjasn/pages/articleviewer.aspx?year=9900&issue=00000&article=00425&type=Abstract). Clinical Journal of the American Society of Nephrology, July 16, 2024. DOI: 10.2215/CJN.0000000000000524

-   Cramer J Kallem, Alaa A Alghwiri, Jonathan G Yabes, Maria-Eleni Roumelioti, Sarah Erickson, Bruce L Rollman, Steven Weisbord, Mark Unruh, Yoram Vodovotz, Manisha Jhamb, Jennifer L Steel. [Association of Symptoms and Collaborative Care Intervention (TĀCcare) with Systemic Inflammation Biomarkers in End-Stage Kidney Disease](https://journals.lww.com/kidney360/abstract/9900/association_of_symptoms_and_collaborative_care.431.aspx). Kidney360, July 16, 2024. DOI: 10.34067/KID.0000000000000512

-   Jhamb, M., Weltman, M. R., Devaraj, S. M., Lavenburg, L. M. U., Han, Z., **Alghwiri, A. A.**, ... & Yabes, J. G. (2024). [Electronic Health Record Population Health Management for Chronic Kidney Disease Care: A Cluster Randomized Clinical Trial](https://jamanetwork.com/journals/jamainternalmedicine/article-abstract/2817606). JAMA Internal Medicine.

-   Al-Zaiti, S. S., **Alghwiri, A. A.**, Hu, X., Clermont, G., Peace, A., Macfarlane, P., & Bond, R. (2022) [A clinician’s guide to understanding and critically appraising machine learning studies: a checklist for Ruling Out Bias Using Standard Tools in Machine Learning (ROBUST-ML)](https://academic.oup.com/ehjdh/article/3/2/125/6567505). European Heart Journal-Digital Health, 3(2), 125-140

-   Alghwiri, A. A., Almomani, F., **Alghwiri, A. A.**, & Whitney, S. L. (2021). [Predictors of sleep quality among university students: the use of advanced machine learning techniques](https://link.springer.com/article/10.1007/s11325-020-02150-w). Sleep and Breathing, 25, 1119-1126

### Published abstracts and proceedings:

-   M.R. Weltman, A.A. Alghwiri, Z. Han, L.U. Lavenburg, T.D. Nolin, J.G. Yabes,, Y. Chen, M. Jhamb. **Prediction of medication therapy problems in patients with moderate- to high-risk chronic kidney disease**: American Society of Nephrology (ASN) 2024
-   Linda-Marie Lavenburg, Zhuoheng Han, Mitra Mosslemi, Alaa Alghwiri, Thomas Nolin, Melanie Weltman, Jonathan Yabes, Manisha Jhamb. **Impact of Population Health Management to Modify Disparate Use of SGLT2i/GLP1Ras**: American Society of Nephrology (ASN) 2024

-   Kallem CJ, Roumelioti M, **Alghwiri AA**, Yabes JG, Jhamb M, Unruh M. **Day-to-day and diurnal variations in patient-reported symptoms among patients on dialysis**. Poster presentation at: National Kidney Foundation 2024 Spring Clinical Meetings. May 14-18, 2024; Long Beach, CA. Abstract ID: 4454

-   Kallem CJ, **Alghwiri AA**, Yabes JG, Roumelioti M, Erickson S, Unruh M, Vodovotz Y, Jhamb M, Steel JL. **Associations between pain, depression, fatigue, and cytokines in patients with end-stage kidney disease**. Poster presentation at: Society of Behavioral Medicine 45th Annual Meeting & Scientific Sessions. March 13-16, 2024; Philadelphia, PA. Abstract ID: 1623084

-   Manisha Jhamb, Melanie Weltman, Susan Devaraj, Linda-Marie Lavenburg, Zhuoheng Han, **Alaa Alghwiri**, Gary Fischer, Bruce Rollman, Thomas Nolin, Jonathan Yabes. **Electronic Health Record based Population Health Management to optimize care in CKD: A Cluster Randomized Clinical Trial (Kidney CHAMP)**: American Society of Nephrology (ASN) 2023; Philadelphia, PA

-   MR Weltman, Z Han, **AA Alghwiri**, J Yabes, LU Lavenburg, TD Nolin, M Jhamb. **Use of guideline-recommended medication therapy in a high-risk chronic kidney disease population in the Kidney CHAMP trial**: American Society of Nephrology (ASN) 2023; Philadelphia, PA

-   Susan M. Devaraj, Jonathan Yabes, **Alaa Alghwiri**, Manqi Cai, Linda-Marie Lavenburg, Khaled Abdel-Kader, Manisha Jhamb. **A demographic and community characteristic comparison of advanced chronic kidney disease patients seeing versus not seeing a nephrologist**: American Society of Nephrology (ASN) 2022; Tampa, FL

-   **Alghwiri, A.**, Wang, S., & Coleman, J. D. (2017). [University Parking System Analysis through Discrete Event Simulation](https://www.proquest.com/openview/1bb9ff8c47fc346eb92027ee4a7e6d6d/1?pq-origsite=gscholar&cbl=51908). In IIE Annual Conference. Proceedings (pp. 2039-2044). Institute of Industrial and Systems Engineers (IISE)

-   **Alghwiri, A.**, Wang, S., & Coleman, J. D. (2017). [Modeling and Optimizing University Shuttle Bus System through Bus Diversions](https://www.proquest.com/openview/74104a40bb8800da7bd6b257a3e082c5/1?pq-origsite=gscholar&cbl=51908). In IIE Annual Conference. Proceedings (pp. 2045-2050). Institute of Industrial and Systems Engineers (IISE)